[package]
name = "monrs"
version = "0.2.0"
authors = ["Alex Yosifov <sashomasho@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10"
anyhow = "1.0.75"
env_logger = "0.10.0"
log = "0.4.20"
